#ifndef MOGL_HPP
#define MOGL_HPP
#include "AnimatedSprite.hpp"
#include "Camera.hpp"
#include "Drawable.hpp"
#include "InputHandler.hpp"
#include "Mesh.hpp"
#include "Model.hpp"
#include "MultimediaOGL.hpp"
#include "MusicManager.hpp"
#include "Rectangle.hpp"
#include "Shader.hpp"
#include "ShaderProgram.hpp"
#include "ShaderProgramManager.hpp"
#include "SoundManager.hpp"
#include "Sprite.hpp"
#include "SpriteAnimationManager.hpp"
#include "TextureManager.hpp"
#endif /* ifndef MOGL_HPP */
